### ISSUE TITLE
Trying to Demodulate in soft mode fails

### ISSUE THREAD

**Issue by eSoares** [veeresht/CommPy#65]
Trying to change the "hard" demodulate in the example in `commpy/examples/conv_encode_decode.py` to "soft" fails with `AttributeError: 'QAMModem' object has no attribute 'symbol_mapping'`.

**Comment by BastienTr** [comment]
6e2f88e1fb32163bb7eebe458249e1f0c76d1890 solve this syntaxe issue that was introduced in a6c731b02643f83d20df0ffa8afa4db328bc447d.

I updated the example file to demonstrate how to compare hard and soft demodulation.
